import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
// components/Layout.jsx
// import Footer from './companents/Footer';
// // components/Layout.jsx


// const RootLayout = ({ children }) => {
//   return (
//     <>
//       {/* istəsən buraya Header də əlavə edə bilərsən */}
//       <main>{children}</main>
//       <Footer />
//     </>
//   );
// };

// export default RootLayout;
// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <main>{children}</main>
//         <Footer />
//       </body>
//     </html>
//   );
// }

